 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/linkers", type: :request do
  # Linker. As you add validations to Linker, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Linker.create! valid_attributes
      get linkers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      linker = Linker.create! valid_attributes
      get linker_url(linker)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_linker_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      linker = Linker.create! valid_attributes
      get edit_linker_url(linker)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Linker" do
        expect {
          post linkers_url, params: { linker: valid_attributes }
        }.to change(Linker, :count).by(1)
      end

      it "redirects to the created linker" do
        post linkers_url, params: { linker: valid_attributes }
        expect(response).to redirect_to(linker_url(Linker.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Linker" do
        expect {
          post linkers_url, params: { linker: invalid_attributes }
        }.to change(Linker, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post linkers_url, params: { linker: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested linker" do
        linker = Linker.create! valid_attributes
        patch linker_url(linker), params: { linker: new_attributes }
        linker.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the linker" do
        linker = Linker.create! valid_attributes
        patch linker_url(linker), params: { linker: new_attributes }
        linker.reload
        expect(response).to redirect_to(linker_url(linker))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        linker = Linker.create! valid_attributes
        patch linker_url(linker), params: { linker: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested linker" do
      linker = Linker.create! valid_attributes
      expect {
        delete linker_url(linker)
      }.to change(Linker, :count).by(-1)
    end

    it "redirects to the linkers list" do
      linker = Linker.create! valid_attributes
      delete linker_url(linker)
      expect(response).to redirect_to(linkers_url)
    end
  end
end
